"""add DocumentExtraction

Revision ID: 4bedcf10f8ca
Revises: 6586f445f1e1
Create Date: 2025-06-13 23:57:03.395600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bedcf10f8ca'
down_revision: Union[str, None] = '6586f445f1e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_extraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=True),
    sa.Column('extracted_fields', sa.JSON(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_extraction_id'), 'document_extraction', ['id'], unique=False)
    op.create_index(op.f('ix_document_extraction_user_id'), 'document_extraction', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_extraction_user_id'), table_name='document_extraction')
    op.drop_index(op.f('ix_document_extraction_id'), table_name='document_extraction')
    op.drop_table('document_extraction')
    # ### end Alembic commands ###
