"""Add blob_url to Document

Revision ID: 9ff8713705b8
Revises: 2221de088b9d
Create Date: 2025-06-17 17:44:22.735623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff8713705b8'
down_revision: Union[str, None] = '2221de088b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('blob_url', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.alter_column('documents', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'domain',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               nullable=False)
    op.alter_column('documents', 'name',
               existing_type=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               nullable=False)
    op.alter_column('documents', 'filename',
               existing_type=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'filename',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('documents', 'name',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('documents', 'domain',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
    op.alter_column('documents', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'blob_url')
    # ### end Alembic commands ###
